// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApp.TodoData;

#nullable disable

namespace TodoApp.TodoData.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoApp.TodoData.Cpr", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("CprBcrypt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CprKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CprPbkdf2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("CprKey")
                        .IsUnique();

                    b.ToTable("Cprs");
                });

            modelBuilder.Entity("TodoApp.TodoData.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CprNr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CprNr");

                    b.ToTable("Todos", (string)null);
                });

            modelBuilder.Entity("TodoApp.TodoData.Todo", b =>
                {
                    b.HasOne("TodoApp.TodoData.Cpr", "Cpr")
                        .WithMany()
                        .HasForeignKey("CprNr")
                        .HasPrincipalKey("CprPbkdf2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpr");
                });
#pragma warning restore 612, 618
        }
    }
}
