// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApp.TodoData;

#nullable disable

namespace TodoApp.TodoData.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20250828180243_HashCpr_Docker")]
    partial class HashCpr_Docker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoApp.TodoData.Cpr", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("CprNr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("UserId");

                    b.HasIndex("CprNr")
                        .IsUnique();

                    b.ToTable("Cprs");
                });

            modelBuilder.Entity("TodoApp.TodoData.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CprNr")
                        .IsRequired()
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CprNr");

                    b.ToTable("Todos", (string)null);
                });

            modelBuilder.Entity("TodoApp.TodoData.Todo", b =>
                {
                    b.HasOne("TodoApp.TodoData.Cpr", "Cpr")
                        .WithMany()
                        .HasForeignKey("CprNr")
                        .HasPrincipalKey("CprNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpr");
                });
#pragma warning restore 612, 618
        }
    }
}
